### ISSUE TITLE
website and domaindynamicclamp.com down?

### ISSUE THREAD

**Issue by mgiugliano** [nsdesai/dynamic_clamp#10]
I volunteer (if you still have the website content) to adapt/turn it into GitHub pages website.

**Comment by nsdesai** [comment]
Thanks for the offer. Andrew Scallon ([his website](https://optogeneticsandneuralengineeringcore.gitlab.io/ONECoreSite/)) from University of Colorado made the same offer a few months ago (though, using Gitlab rather than Github).

https://optogeneticsandneuralengineeringcore.gitlab.io/dynamicclampsite/

**Comment by mgiugliano** [comment]
Fantastic!!!!!!!!!!!!! Thank you all.

**Comment by christianrickert** [comment]
@mgiugliano We've just published some work with the hardware designed by @nsdesai using our custom control software ([dyClamp](https://github.com/christianrickert/dyClamp)/[pyClamp](https://github.com/christianrickert/pyClamp)) - https://doi.org/10.1085/jgp.202213193

**Comment by nsdesai** [comment]
Very nice. Thanks for the reference, @christianrickert . Thanks also for using the term "funny current"! I've always liked that name, even though it's not used that much anymore in neuro papers.

**Comment by christianrickert** [comment]
@nsdesai You're very welcome!
